### ISSUE TITLE
[BUG]: Image not show after reload

### ISSUE THREAD

**Issue by paulussimanjuntak** [KRRISH96/render-smooth-image-react#2] opened 2020-06-06 10:58 UTC
**Describe the bug**
I have following the instruction, but the images is always loading.

**To Reproduce**
1. nextjs project

**Expected behavior**
after reload the image will show

**Screenshots**
<img width="1195" alt="Screen Shot 2020-06-06 at 18 57 55" src="https://user-images.githubusercontent.com/38719572/83942614-b14c9b00-a827-11ea-81d4-db3341132388.png">

**Comment by KRRISH96** [comment] 2020-06-06 11:05
@paulussimanjuntak 
Thanks for reporting.
Sorry for the inconvenience.

This is a known bug(only for SSR), caused after fixing #1 
The problem is with onLoad event in the component, I am looking for the best way to fix this.

**Possible cause:**
After the first load images will be served from cache thus not triggering the onLoad again.

Feel free to raise a PR if you want to take up this issue.

**Comment by KRRISH96** [comment] 2020-06-06 11:57
Fixed in `v1.0.0`

Fix [commit](https://github.com/KRRISH96/render-smooth-image-react/commit/5cf6c19bc5a4a68a9d14728f547686a1865e7c96)

Closing issue

**Closed as completed by KRRISH96** 2020-06-06 11:57 UTC
Labels: bug

**Comment by paulussimanjuntak** [comment] 2020-06-06 12:08
hi @KRRISH96 , are you sure is this work now in nextjs?
I'm just redownloading the package and it's still like before...
<img width="1195" alt="Screen Shot 2020-06-06 at 20 11 33" src="https://user-images.githubusercontent.com/38719572/83943873-f4ac0700-a831-11ea-9374-1fb023cdecd4.png">

**Comment by KRRISH96** [comment] 2020-06-06 12:14
@paulussimanjuntak 
Have you tried clearing the cache and load with a fresh build?

It would be helpful if you can provide me with a reproducible repo or sandbox so I could try and see why it's failing.

Thanks!

**Comment by paulussimanjuntak** [comment] 2020-06-06 12:17
@KRRISH96 Thankyou so much it's work :))

**Comment by KRRISH96** [comment] 2020-06-06 12:19
@paulussimanjuntak

Glad I could help! 😊

**Comment by paulussimanjuntak** [comment] 2020-06-06 12:25
@KRRISH96 is there a way to add an css class to the image?
